# Generated by Django 3.0.4 on 2020-04-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='profile_Pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
